### ISSUE TITLE
Feature: Nova logo no twitter

### ISSUE THREAD

**Issue by vcwild** [aHub-Tech/Live-Divulgador#29]
Proponho a criação de uma nova logo para o live divulgador no Twitter.

[Referencia](https://twitter.com/LiveDivulgador/photo)

**Comment by ttiagojm** [comment]
Boa ideia @DevRadhy a versão colorful para o twitter de artes e a minimal para tech.

Coloquei lá: twitter.com/LiveDivulgador | twitter.com/LiveDivulgador2

Digam o que acham

**Comment by vcwild** [comment]
A logo é muito legal e limpa, só que como o twitter usa a bordas arredondadas fica muito espaço vazio. Talvez faça mais sentido fazer a logo simétrica (antenas iguais e mais curtas) pra que possa dar mais zoom e otimizar o espaço utilizado.

**Comment by vcwild** [comment]
Resolvido, implementado.
