### ISSUE TITLE
Bug: Filtrar streamers que atendam apenas as categorias divulgáveis

### ISSUE THREAD

**Issue by vcwild** [aHub-Tech/Live-Divulgador#39]
Edit: inserido makers & crafting
> Faltou o Makers & Crafting @vcwild

## O que precisa ser feito?

- Deve ser apenas twitado os streamers que estiverem nas categorias:
  - Software & Game Development
  - Science & Technology
  - Podcast & Talk Shows
  - Art
  - Makers & Crafting

**Comment by ttiagojm** [comment]
Faltou o Makers & Crafting @vcwild 

O Podcast & Talk shows é divulgado com base na categoria do streamer. Se ele entrou para o banco como "art" então será divulgado no LiveDivulgador2, caso esteja como "code" é divulgado no LiveDivulgador.

Caso isso não seja prático de ser implementado na nova lógica do bot, removam a categoria Podcast & Talk shows e deixem as outras.

Aliás, esqueci-me de perguntar, a parte de o bot divulgar em 2 contas do Twitter (como estava a funcionar anteriormente) é possível ?

**Comment by vcwild** [comment]
A lógica do bot agora é bem mais simples, ele lida com todos os streamers que ele fizer a query de leitura. Se um dos streamers dessa seleção entra em live e é numa categoria válida ele vai divulgar. Ou seja, antes mesmo do bot iniciar a rotina ele já sabe quem ele precisa pesquisar.

A implementação é assim justamente pra simplificar a lógica de desenvolvimento, dessa forma conseguimos controlar o fluxo de execução e facilitar os testes (poucos ifs no corpo de funções = poucos efeitos colaterais possíveis).

Outra vantagem é que se formos criar novos bots (divulgador 3, 4, 5, etc.) com novas categorias, é só replicar a instância existente do bot livedivulgador e ajustar o filtro para essas novas categorias. Dessa forma temos uma arquitetura que escala horizontalmente (vários bots com regras de negócio diferentes).

**Comment by vcwild** [comment]
Há ainda mais uma ressalva, que é a possibilidade de criarmos um front-end onde as pessoas vão poder se cadastrar, aí esse front vai tentar se comunicar com a API do banco e vai adicionar esse novo streamer sem precisarmos fazer nada na mão.

Ainda estamos planejando esse front, então por enquanto não temos previsão.

**Comment by ttiagojm** [comment]
Ah, então caso fosse necessário divulgar para outra conta teriamos de usar 2 instâncias.

Fantástica essa ideia do front-end !

**Comment by vcwild** [comment]
> Ah, então caso fosse necessário divulgar para outra conta teriamos de usar 2 instâncias.
> 
> Fantástica essa ideia do front-end !

Exato, a parte massa é que cada instância pode ter testes completamente isolados!!
