### ISSUE TITLE
Bug: Script de instalação do projeto não está funcionando corretamente

### ISSUE THREAD

**Issue by vcwild** [aHub-Tech/Live-Divulgador#46]
> Não consegui fazer rodar
> 
> ### Attempt 1
> ```shell
> rodrigo@linux:~/projetos/Live-Divulgador$ sh scripts/install.sh 
> scripts/install.sh: 3: source: not found
> scripts/install.sh: 6: print_header: not found
> scripts/install.sh: 9: print_check: not found
> ```
> 
> ### Attempt 2
> ```shell
> rodrigo@linux:~/projetos/Live-Divulgador$ ./scripts/install.sh 
> 
> -- Preparing python virtual environment 
> [ KO ] virtualenv initialization /home/rodrigo/projetos/Live-Divulgador/venv
> [ KO ] pip upgrade
> [ KO ] pip install setuptools_scm
>        ... installing livedivulgador bot component
> [ KO ] livedivulgador bot installation
>        ... checking CLI
> [ KO ] livedivulgador CLI installation
> ```
_Originally posted by @RodrigoDornelles_

Try using `chmod +x ./scripts/install.sh` before running the script

_Originally posted by @vcwild in https://github.com/aHub-Tech/Live-Divulgador/issues/43#issuecomment-974733364_

**Comment by RodrigoDornelles** [comment]
now
```scripts/install.sh: 3: source: not found
scripts/install.sh: 6: print_header: not found
scripts/install.sh: 9: print_check: not found
scripts/install.sh: 12: print_check: not found
scripts/install.sh: 15: print_check: not found
-e        ... installing  bot component
scripts/install.sh: 20: print_check: not found
-e        ... checking CLI
scripts/install.sh: 25: print_check: not found
```

**Comment by vcwild** [comment]
@RodrigoDornelles vou tentar usar makefile como solução alternativa, não consegui encontrar o motivo do setup não estar funcionando no shell normalmente

**Comment by vcwild** [comment]
Continues in #47

**Comment by RodrigoDornelles** [comment]
@vcwild bora marcar uma call e tentar fazer rodar
