### ISSUE TITLE
Feature: Possibilidade de adicionar mais streamers no banco de dados

### ISSUE THREAD

**Issue by ttiagojm** [aHub-Tech/Live-Divulgador#57]
Apesar de o bot divulgar grande parte das pessoas streamers, há sempre algumas pessoas novas fazendo stream e no caso tenho 2 que gostava de convidar para entrar no banco de dados.

Como posso adicioná-las no banco (se for possível para a infra claro) ?

**Comment by ttiagojm** [comment]
@aHub-Tech/devops

**Comment by vcwild** [comment]
Fala tiago. Essa feature precisa ser finalizada. A forma mais simples de implementar isso seria via terminal com `livedivulgador add streamer [twitch-username] [twitter-username]`

Esse comando vai resolver todos os passos para atualizar a base de dados com um novo streamer.

Mas para que isso aconteça, ainda precisamos resolver alguns passos.

O que temos hoje:

- Método que resolve [twitch ID quando é dado o twitch username](https://github.com/aHub-Tech/Live-Divulgador/blob/main/livedivulgador/twitch/client.py#L80)
- [Service que cria novos streamers na base de dados](https://github.com/aHub-Tech/Live-Divulgador/blob/main/livedivulgador/service/streamers_service.py#L28)

O que precisamos:

- Método que resolve twitter ID quando é dado twitter username
- Um script que executa a ação de criar novo streamer pedida pela CLI do livedivulgador e deve ser armazenado no `main.py`

O protótipo desse script seria algo do tipo:

```python
@main.command("create")
@main.argument('twitch_name', nargs=-1)
@main.argument('twitter_name', nargs=1)
def create(twitch_name: str, twitter_name: str) -> None:
    twitch_id = TwitchClient(...).get_streamer_id(twitch_name)
    twitter_id = TwitterClient(...).get_twitter_id(twitter_name)
    streamer = Streamer(twitch_id=twitch_id, twitter_id=twitter_id, name=twitch_name)
    StreamersService.create_streamer(streamer)
```

**Comment by vcwild** [comment]
Essa issue está sendo bloqueada pela #60
