### ISSUE TITLE
Bug: Conexão de rede instável na Azure

### ISSUE THREAD

**Issue by vcwild** [aHub-Tech/Live-Divulgador#58]
@aHub-Tech/devops 

O bot do Livedivulgador está tendo algumas instabilidades na VPS da Azure nos últimos tempos.Houveram 3 falhas críticas de execução em 1 semana.

Suponho que esse tipo de falha provavelmente está acontecendo por causa da infra, pois nunca enfrentamos essas situações na nossa infra anterior (Digital Ocean).

Vou atualizar essa issue caso se repita, e nesse caso trarei o logger do bot.

**Comment by ttiagojm** [comment]
Aconteceu novamente, o bot não tweeta há 21 horas, sendo que já houve lives nesse período.
